spring.application.name=PosBarLacteo


# Conexión a la base de datos de Railway
spring.datasource.url=jdbc:mysql://root:YDJkAxWxcZnOrxMqsiLBGKJJPvLJrOza@tramway.proxy.rlwy.net:43917/railway
spring.datasource.username=root
spring.datasource.password=YDJkAxWxcZnOrxMqsiLBGKJJPvLJrOza

# Para que Hibernate cree las tablas automáticamente basándose en tus clases Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true