spring.application.name=PosBarLacteo

# Cambiamos el endpoint de AWS por localhost como valor por defecto
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/posbarlacteo?useSSL=false&serverTimezone=UTC}

# Aquí pones tu usuario local (usualmente root)
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}

# IMPORTANTE: Reemplaza 'tu_password_local' por la clave que le pusiste a tu MySQL local
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

# Para que Hibernate cree las tablas automáticamente basándose en tus clases Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true