name: Deploy Backend to EC2 with Docker Hub

on:
  push:
    branches:
      - main # Cambia a master si tu rama principal se llama así

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar Código
        uses: actions/checkout@v4

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y Subir Imagen Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mi-backend:latest

      - name: Desplegar en EC2 de AWS Academy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_BACKEND_HOST }}
          username: ${{ secrets.EC2_BACKEND_USER }}
          key: ${{ secrets.EC2_BACKEND_KEY }}
          script: |
            # Descargar la nueva versión desde Docker Hub
            docker pull ${{ secrets.DOCKER_USERNAME }}/mi-backend:latest
            
            # Detener contenedores anteriores para liberar el puerto
            docker stop backend-app || true
            docker rm backend-app || true
            
            # Encender el contenedor inyectando los datos de la base de datos RDS de CloudFormation
            # NOTA: Mapeamos el puerto 3000 de la EC2 al 3000 del contenedor (ajústalo si usas otro)
            docker run -d -p 3000:3000 --name backend-app \
              -e DB_HOST="mi-base-datos-lab.cv1y27electk.us-east-1.rds.amazonaws.com" \
              -e DB_USER="admin" \
              -e DB_PASSWORD="Password123!" \
              -e DB_NAME="tu_nombre_de_base_de_datos" \
              ${{ secrets.DOCKER_USERNAME }}/mi-backend:latest